### ISSUE TITLE
Implement Search Feature

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#39]
Use CDC to index title and name and send data into elastic

Add a new service to search in elastic

Add the ui

**Comment by mmamadilov** [comment]
[feature/Elastic_search](https://github.com/mapr-demos/mapr-music/tree/feature/Elastic_search) branch contains the recent changes. [ElasticSearch doc](https://github.com/mapr-demos/mapr-music/blob/feature/Elastic_search/doc/elastic-search.md) explains how to setup environment. Here is link to [pull request](https://github.com/mapr-demos/mapr-music/pull/63) into master.
