### ISSUE TITLE
CDC : define the proper data model

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#58]
We should have a single change_log for all application events:

```
maprcli stream create -path /mapr_music_changelog -ischangelog true -consumeperm p
```

Then create 2 topics for the tables:

```
$ maprcli table changelog add -path /apps/albums -changelog  /mapr_music_changelog:albums

$ maprcli table changelog add -path /apps/albums -changelog  /mapr_music_changelog:artist

```

* [x] Create the new topics and log
* [x] Adapt the source code
* [x] Update the document with this new info

**Comment by mmamadilov** [comment]
[feature/Recommendation_engine](https://github.com/mapr-demos/mapr-music/tree/feature/Recommendation_engine) contains all changes.
