### ISSUE TITLE
UI : Album and Artist Create buttons should be on the main pages

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#59]
UI : Album and Artist Create buttons should be on the main pages

We need to add "Create Button" on the artists and album home page

**Comment by mmamadilov** [comment]
Recent changes can be found at [feature/Create_buttons_fix](https://github.com/mapr-demos/mapr-music/tree/feature/Create_buttons_fix) branch. Here is link to [pull request](https://github.com/mapr-demos/mapr-music/pull/62) into master.
