### ISSUE TITLE
Implement Recommendation Engine with Spark

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#61]
1. we need more data, ideally capture/importa "ratings"

2. then analyze with spark the ratings per user "type" to create the model

3. apply the model in real time

see
https://mapr.com/ebooks/spark/08-recommendation-engine-spark.html

**Comment by tdunning** [comment]
The million song database has a listener history database from last.fm that should provide a sufficient dataset.

https://labrosa.ee.columbia.edu/millionsong/lastfm

**Comment by tdunning** [comment]
I would recommend that an alternative implementation of the recommender be used.

See https://mapr.com/practical-machine-learning/ for the theory.

See https://mahout.apache.org/users/algorithms/intro-cooccurrence-spark.html

Also https://www.slideshare.net/sscdotopen/cooccurrence-based-recommendations-with-mahout-scala-and-spark

And https://mapr.com/blog/inside-look-at-components-of-recommendation-engine/

This approach is much simpler to deploy for making real recommendations using a search engine.

**Comment by tdunning** [comment]
Note that *this* is where the play history data is:

https://labrosa.ee.columbia.edu/millionsong/tasteprofile

**Comment by tgrall** [comment]
Reopening to track the work.
Thanks Ted for the link

**Comment by mmamadilov** [comment]
[Pull request](https://github.com/mapr-demos/mapr-music/pull/79) successfully merged and closed. All changes can be found at [master branch](https://github.com/mapr-demos/mapr-music).
