### ISSUE TITLE
edit buttons : add/edit/delete should be visible even when screen is small

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#64]
edit buttons : add/edit/delete should be visible even when screen is small

in some case the buttons to edit/add albums and artists are not visible on the screen
they are off on the right

we need to be sure they are always visible

**Comment by mmamadilov** [comment]
Buttons responsive markup bug is fixed. [Pull request](https://github.com/mapr-demos/mapr-music/pull/70) is merged successfully into [master](https://github.com/mapr-demos/mapr-music).
