### ISSUE TITLE
Add Rating capabilities

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#75]
Add Rating capabilities

* [x] user should be able to add ratings for albums and artists
  * [x] Create the REST Interface
  * [x] Expose it in the UI

* [x] Write a small script (step by step in a doc) to be able to see how the rating of a user can influence the model.

* [x] Show how to run manually the model
* [x]  Explain and show how to automatically run the mode on the fly "streaming" using CDC (need to checkthat is is possible without redoing the whole spark job)

**Comment by mmamadilov** [comment]
[feature/Recommendation_engine](https://github.com/mapr-demos/mapr-music/tree/feature/Recommendation_engine) branch contains all changes.
