### ISSUE TITLE
Initializing statistis and elastic from existing data

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#76]
IN the current and first implementation, the Statistics and Elastic services must be up and running before importing the data.

In the way we have built the application, we have added the services "after" the application has been created.

We need to improve the services to let them initialize the data (stats & index) from an existing & imported dataset.

Some proposal, that does not necesary works when the system is fully live and active (meanin when data are changing):

* [ ]  if the statistic table is empty let's do the job to count all data
* [ ] add a way to reinitialize the stat
* [ ] if the index is empty let's run the full table scan and index all data

**Comment by vladglinskiy** [comment]
* ElasticSearch service changed to support index reinitialization via '-r' option:
`java -jar elasticsearch-service-1.0-SNAPSHOT.jar -r`
* Statistic service changed to recount number of documents on each redeploy
* `/mapr-music-rest/api/1.0/statistics` endpoint allows to recompute the statistics

All changes can be found at [feature/Recommendation_engine](https://github.com/mapr-demos/mapr-music/tree/feature/Recommendation_engine) branch.
