### ISSUE TITLE
Tutorial: show dynamic schema with adding "updated by XXX on XXX"

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#78]
The idea of this issue to to provide an complete step in the tutorial about the power of the flexible schame

It is very ieasy to add a new feautre that change the schema.

for example:
- PO/marketing ask "Can you now, add the iformation about the user that creates the document, and or the last modification of the document"

The result:

add new entry in all document, WHEN UPDATED OR CREATED (not bu default, not existing at the beginning), that is for example:

````json
{
 // albun or any other doc
 
 // API should add
 "update_information" : {
     "date_of_operation" : 23423423,
     "user_id" : "music"
 }

}

````
Ideally not part of the Java Bean, should be added on isnert/update and just store in DB for "technical reason" not exposed in the global API

**Comment by mmamadilov** [comment]
All changes can be found at [devel](https://github.com/mapr-demos/mapr-music/tree/devel) branch.
