### ISSUE TITLE
Generate Data Set and Upload it into GIT

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#84]
We need to make data available.

* [x] Upload the data as compress file 
* [x] Create a doc explaining how to import data (simpler and shorted than the generate data)
* [x] check that all ratings could be imported (we can create a  .sh file)

**Comment by mmamadilov** [comment]
All changes can be found at [devel](https://github.com/mapr-demos/mapr-music/tree/devel) branch.
