### ISSUE TITLE
Move Streams to /apps/ folder

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#85]
The change log is located in /

see https://github.com/mapr-demos/mapr-music/blob/master/doc/change-data-capture.md

We need to move it in the /apps/ folder
```
 maprcli stream create -path /apps/mapr_music_changelog -ischangelog true -consumeperm p
```
* [x] Update application code and configuration
* [x] Update documentation

**Comment by mmamadilov** [comment]
All changes can be found at [devel](https://github.com/mapr-demos/mapr-music/tree/devel) branch.
