### ISSUE TITLE
Reorganize the docs into a tutorial

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#87]
Create a tutorial for MapR-Music to drive developer towards the various steps:

(put this in `/doc/tutorials`  folder )

## 3 - Setup 

* Install MapR (keep in empty as we will use MapR Containers and VMs)
* Install MapR client (explain the basis)

## 4 - Import the Data Set

* Explain the dataset
* Import Datas

## 5 - Working with MapR-DB

* Show MapR DB Shell to query some documents
* Update document
* Create Document
* Show MapR Drill to query some document

## 6 - Working with Java

* Explain Maven Dependennces
* Show basic code snipplet

* Calling Drill from Java
* JDBC Setup

## 7 - Create a REST API

* Explain the API and the layer of the implementation
* Show the basic
* Prepare code for Wildfly

## 8 - Deploy to Java EE (Wildfly)

* Explain Modules
* show CURL operations to use the API

## 9 - Building a UI with Angular

* Explain the basics

## 10 - Working Arrays

* explain the arrays manipulation

## 11 - CDC

* explain the 3 uses cases we have:
  * Statistics
  * Delete Artistis
  * Elastic Integration

* Show the code

**Comment by vladglinskiy** [comment]
All changes can be found at [devel](https://github.com/mapr-demos/mapr-music/tree/devel) branch.
