### ISSUE TITLE
Add new tutorials step for Machine Learning/Recommendations

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#88]
Document spark, ML, recmmendations in the tutorial

**Comment by mmamadilov** [comment]
[Creating Recommendation Engine](https://github.com/mapr-demos/mapr-music/blob/devel/doc/tutorials/012-creating-recommendation-engine.md) tutorial step added. All changes can be found at [devel branch](https://github.com/mapr-demos/mapr-music/tree/devel).
