### ISSUE TITLE
Change the docker setup to allow  application to be restarted

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#98]
We need to change the way JBOSS is started in docker since it is not possible to restart the container.

To test:

1. Deploy the application in a docker PACC
2. connect the application, everything works
3. stop and start the container

You will see some exception, my quick analysis is that we try to redeploy the application and it does not work due to the mapr shared library

**Comment by mmamadilov** [comment]
[run.sh](https://github.com/mapr-demos/mapr-music/blob/master/bin/run.sh#L34) script changed to allow to restart Docker container.
